name: Deployment - Reusable Workflow

on:
    workflow_call:
        inputs:
          mongodb-uri:
            required: true
            type: string
          kubectl-version:
            description: Provide the required kubectl version
            default: v1.26.0
            required: false
            type: string
          k8s-manifest-dir:
            description: Directory containing kubernetes manifests files
            default: kubernetes/
            required: true
            type: string
          environment:
            description: Provide the Deployment Environment
            default: dev
            required: true
            type: string
        secrets:
          k8s-kubeconfig:
            required: true
          mongodb-password:
            required: true

jobs:
    reuse-deploy:
        environment:
            name: ${{inputs.environment}}
            url: https://${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        outputs: 
            APP_INGRESS_URL: ${{steps.set-ingress-host-address.outputs.APP_INGRESS_HOST}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v4
              with:
                version: '${{inputs.kubectl-version}}'

            - name: Set Kubeconfig file
              uses: azure/k8s-set-context@v3
              with:
                method: kubeconfig
                kubeconfig: ${{secrets.k8s-kubeconfig}}

            - name: Fetch Kubernetes Cluster Details
              run: |
                kubectl version --short -o yaml
                echo -----------------------------
                kubectl get nodes

            - name: Save Nginx Ingress Controller IP as GITHUB env variable
              run: |
                echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o  jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

            - name: Replace token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '${'
                tokenSuffix: '}'
                files: '["${{inputs.k8s-manifest-dir}}/*.yaml"]'
              env:
                NAMESPACE: ${{vars.NAMESPACE}}
                REPLICAS: ${{vars.REPLICAS}}
                K8S_IMAGE: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
                INGRESS_IP: ${{env.INGRESS_IP}}

            - name: Check files
              run: |
                cat ${{inputs.k8s-manifest-dir}}/*.yaml

            - name: Create MongoDB secret
              run: |
                kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{inputs.mongodb-uri}} \
                --from-literal=MONGO_USERNAME=${{env.MONGO_USERNAME}} \
                --from-literal=MONGO_PASSWORD=${{secrets.mongodb-password}} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -

            - name: Deploy to Dev Env
              run: |
                kubectl apply -f ${{inputs.k8s-manifest-dir}}
            
            - name: Set App Ingress Host Url
              id: set-ingress-host-address
              run: |
                echo "APP_INGRESS_HOST=$(kubectl -n ${{vars.NAMESPACE}} get ingress -o  jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> $GITHUB_OUTPUT
